### ISSUE TITLE
API buy issue 

### ISSUE THREAD

**Issue by manishkumar1601** [fckveza/Selfbot-Whatsapp#3]
i am from india and i am student and new developer i have usd and inr currency so how i can buy api from vhtear website bcoz i dont have Indonesian currency or any platform

**Comment by Arifirazzaq2001** [comment]
open the Arifi Razzaq OFFICIAL YouTube channel, and get the WhatsApp bot
script, free APIKEY

Pada tanggal Sen, 14 Jun 2021 11.41 AM, Manish ***@***.***>
menulis:

**Comment by fckveza** [comment]
> i am from india and i am student and new developer i have usd and inr currency so how i can buy api from vhtear website bcoz i dont have Indonesian currency or any platform

Can pay with paypal
